### ISSUE TITLE
Use vim instead of nano

### ISSUE THREAD

**Issue by ejegrova** [ejegrova/linuxadmin#3]
* install vim
* change all nano occurences to vim
* brief description on how to use vim when first encountered

**Comment by ZelenyMartin** [comment]
Upravit _Vytváření souborů_: https://naucse.python.cz/2024/brno-linuxadmin-jaro/carpentry-unix/create/
Zkopírovat z: https://github.com/ZelenyMartin/uvod-do-linuxu/blob/main/prikazova-radka/absolutni-minimum-editoru-vim/absolutni-minimum-editoru-vim.md

**Comment by ejegrova** [comment]
Přidán PR https://github.com/ejegrova/linuxadmin/pull/15, stále je potřeba vytvořit úvodní text k použití vimu.

**Comment by ejegrova** [comment]
https://github.com/ejegrova/linuxadmin/pull/15 mergnuto, můžeš pokračovat :)
