### ISSUE TITLE
Virtualbox installation

### ISSUE THREAD

**Issue by ejegrova** [ejegrova/linuxadmin#5]
Check if lesson 0 - [installation ](https://naucse.python.cz/2024/brno-linuxadmin-jaro/linuxadmin/installation/) works the same way on Windows with Virtualbox.

* update screenshots if needed
* update text if needed

Use fedora 39 workstation image: https://fedoraproject.org/cs/workstation/download

**Comment by boriskolda** [comment]
Updated in #12
