### ISSUE TITLE
Specifikovat používání virtuálky na macOS

### ISSUE THREAD

**Issue by ZelenyMartin** [ejegrova/linuxadmin#8]
https://github.com/ejegrova/linuxadmin/blob/783fc7edf1fcf72f72df9cc72da4f2eb195cd438/lessons/linuxadmin/installation/index.md?plain=1#L35-L43

Kdo příjde s macOS, měl by použít UTM (u arm architektury je to nutnost).

**Comment by tnevrlka** [comment]
Vyřešeno #13. Můžeme uzavřít?

**Comment by ZelenyMartin** [comment]
Díky moc!
